"""All site copy, PT-BR and EN, from "Copy do portfólio - rascunho 1.md".
Missing facts stay as [PREENCHER: ...] / [FILL IN: ...] markers; nothing is invented.
Section titles, nav labels and other microcopy are the only text written for the site itself."""

# Where the lead form posts. Any form backend that accepts a POST of form fields and can answer
# with JSON works (Formspree, Getform, Basin, Web3Forms...). Leave it empty until you have one:
# the form then says it is not connected instead of pretending to send.
LEADS_ENDPOINT = ""
# Extra hidden fields some services require, for example {"access_key": "..."} for Web3Forms.
LEADS_FIELDS = {}

CASE_SLUG = {"pt": "projetos/dmr-info", "en": "en/projects/dmr-info", "es": "es/proyectos/dmr-info"}
DMR_URL = "https://www.dmrinfo.com.br/"

PT = {
    "code": "pt",
    "html_lang": "pt-BR",
    "title": "Erick Souza | Landing Pages de Alta Conversão e Web Design",
    "description": "Designer há mais de 20 anos. Landing pages e sites institucionais que integram identidade visual, UX, motion e código. Atendimento no Brasil e no exterior.",
    "skip": "Pular para o conteúdo",
    "brand": "ERICK SOUZA",
    "studio": ("UI/UX", "MOTION · BRANDING · WEB"),
    "cta_head": "AGENDAR CONVERSA",
    "lang_group_label": "Idioma",
    "nav_label": "Navegação principal",
    "nav": [("projetos", "Projetos"), ("servicos", "Serviços"), ("processo", "Processo"), ("sobre", "Sobre"), ("contato", "Contato")],
    "meter": "PROGRESSO",
    "loader": {"status": "CARREGANDO"},
    "hero": {
        "label": "01 / ERICK SOUZA",
        "lines": ["Landing pages", "projetadas para", "converter visitas"],
        "last_lead": "em ",
        "fault": "clientes.",
        "aria": "Landing pages projetadas para converter visitas em clientes.",
        "sub": "Sou Erick Souza, designer há mais de 20 anos. Integro identidade visual, UX, motion e código em páginas com objetivo claro e foco na ação do visitante.",
        "cta1": "AGENDAR CONVERSA",
        "cta2": "VER PROJETOS",
        "readouts": ["SÃO PAULO / BRASIL", "ATENDIMENTO INTERNACIONAL", "IDENTIDADE · UX · MOTION · CÓDIGO"],
        "call_off": "ROLE PARA CONTINUAR",
        "call_on": "ROLE PARA CONTINUAR",
    },
    "projects": {
        "label": "02 / PROJETOS",
        "aside": "7 TIPOS DE PROJETO / EXEMPLOS EM BREVE",
        "heading": "Tipos de projeto",
        "conceptual": "EXEMPLOS EM BREVE",
        "cards": [
            {"no": "TIPO 01 / SITES INSTITUCIONAIS", "name": ["Sites", "Institucionais"], "desc": "Presença digital completa: empresa, serviços e contato, pensada para gerar confiança.", "real": False},
            {"no": "TIPO 02 / LANDING PAGE", "name": ["Landing", "Page"], "desc": "Página única com um objetivo claro: converter quem chega em lead ou cliente.", "real": False},
            {"no": "TIPO 03 / PÁGINA DE VENDAS", "name": ["Página de", "Vendas"], "desc": "Copy e design estruturados para apresentar a oferta e fechar a venda.", "real": False},
            {"no": "TIPO 04 / PÁGINA DE CAPTURA", "name": ["Página de", "Captura"], "desc": "Página enxuta que troca um contato por algo de valor: e-book, aula ou consultoria.", "real": False},
            {"no": "TIPO 05 / E-COMMERCE", "name": ["E-commerce"], "desc": "Loja virtual com catálogo, checkout e experiência de compra otimizados para conversão.", "real": False},
            {"no": "TIPO 06 / BRANDING", "name": ["Branding"], "desc": "Posicionamento, tom de voz e sistema visual coerentes em todo ponto de contato com a marca.", "real": False},
            {"no": "TIPO 07 / IDENTIDADE VISUAL", "name": ["Identidade", "Visual"], "desc": "Logotipo e elementos gráficos que dão identidade própria à marca.", "real": False},
        ],
        "img_alt": "Página inicial do site da DMR Info, projetada por Erick Souza",
        "placeholder": "[PREENCHER: exemplo]",
        "banner_label": "Visitar o site da DMR Info (abre em nova aba)",
        "banner_cap": "VISITAR O SITE ↗",
    },
    "services": {
        "label": "03 / SERVIÇOS",
        "title": ["Da landing page", "ao e-commerce,", "peça por peça."],
        "items": [
            ("01 / BRANDING", "Branding", "Posicionamento, tom de voz e sistema de marca que sustentam toda a comunicação."),
            ("02 / IDENTIDADE", "Identidade visual", "Logotipo e sistema visual que sustentam o site e tudo o que vem depois."),
            ("03 / PRESENÇA", "Sites institucionais", "A presença digital que apresenta a empresa, o que ela faz e por que merece confiança. Rápida, clara e otimizada para os mecanismos de busca."),
            ("04 / CONVERSÃO", "Landing page", "Uma página, um objetivo. Estrutura, texto, design e código pensados para levar o visitante a uma única ação."),
            ("05 / VENDAS", "Página de vendas", "Copy e design estruturados para apresentar a oferta e fechar a venda."),
            ("06 / CAPTURA", "Página de captura", "Página enxuta que troca um contato por algo de valor: e-book, aula ou consultoria."),
            ("07 / LOJA", "E-commerce", "Loja virtual com catálogo, checkout e experiência de compra otimizados para conversão."),
            ("08 / MOVIMENTO", "Motion e 3D", "Animações e elementos 3D que dão ritmo à página, sem comprometer o desempenho."),
        ],
    },
    "process": {
        "label": "04 / PROCESSO",
        "title": ["Do briefing", "à publicação,", "em um só processo."],
        "lede": "Nenhuma etapa é omitida. Cada fase reduz o retrabalho da seguinte.",
        "ai_note": "Utilizo IA como ferramenta de produtividade. As decisões de estratégia e de design são minhas.",
        "deadline": "PRAZO TÍPICO DE UMA LANDING PAGE: [PREENCHER]",
        "status_step": "PASSO",
        "status_hint": "ROLE PARA AVANÇAR",
        "steps": [
            ("Briefing", "Levantamento do negócio, do público e do que a página precisa alcançar."),
            ("Documentação", "Escopo, entregas e expectativas registrados por escrito."),
            ("Estratégia", "Definição da proposta de valor, do público e da ação principal."),
            ("Wireframe", "Estrutura da página definida antes da estética."),
            ("Copy", "Redação ou revisão dos textos, com função definida para cada bloco."),
            ("Design", "Identidade, tipografia, cor e ritmo visual."),
            ("Prototipação", "Validação de um protótipo navegável antes do início do desenvolvimento."),
            ("Desenvolvimento", "Código limpo, rápido e estruturado para SEO."),
            ("Testes", "Velocidade, acessibilidade, responsividade e formulários."),
            ("Deploy", "Publicação, verificação final e entrega."),
        ],
    },
    "about": {
        "label": "05 / SOBRE",
        "title": ["20+ anos", "de marcas.", "Agora na web."],
        "paras": [
            "Atuo há mais de 20 anos com design de marcas, especialmente logotipos. Aprendi que uma marca eficaz cabe em uma forma simples, e que essa forma só funciona quando comunica com clareza.",
            "Também trabalhei com social media, o que me ensinou a lidar com a atenção curta do público: cada elemento precisa justificar o seu lugar.",
            "Hoje aplico essa experiência ao ambiente digital. Assumo identidade, layout, motion e desenvolvimento, com um único ponto de contato do briefing à publicação.",
            "Levo ao digital o mesmo rigor que sempre apliquei ao trabalho com marcas: cada projeto é conduzido com critério e entregue com cuidado.",
        ],
        "meta": "SÃO PAULO, SP · 20+ ANOS DE DESIGN · UI/UX · MOTION · BRANDING · WEB",
        "portrait": "[PREENCHER: retrato do Erick]",
        "workshop": "[PREENCHER: foto do processo ou da mesa de trabalho]",
    },
    "tools": {
        "label": "06 / FERRAMENTAS",
        "heading": "Ferramentas",
        "quote": "As ferramentas que utilizo em design, motion e desenvolvimento.",
        "groups": [
            ("DESIGN E MOTION", "Figma, Photoshop, Spline, Premiere, CapCut, Topaz Vídeo"),
            ("DESENVOLVIMENTO", "HTML5, CSS3, Sass, JavaScript, TypeScript, React, PHP, MySQL, GSAP, Anime.js, Barba.js, GitHub"),
            ("IA", "Claude Code, ChatGPT, Kling AI"),
        ],
    },
    "contact": {
        "label": "07 / CONTATO",
        "h2_before": "Vamos conversar sobre o projeto da sua ",
        "h2_word": "marca",
        "h2_after": "",
        "text": "Descreva o objetivo do projeto. Respondo com os próximos passos.",
        "button": "AGENDAR CONVERSA →",
        "channels": [
            ("E-mail", "[PREENCHER]"),
            ("WhatsApp", "[PREENCHER]"),
            ("Agendamento", "[PREENCHER]"),
            ("LinkedIn", "Vagas CLT [PREENCHER]"),
            ("GitHub", "[PREENCHER]"),
            ("Behance", "[PREENCHER]"),
            ("Dribbble", "[PREENCHER]"),
            ("Instagram", "[PREENCHER]"),
        ],
        "channels_label": "Canais de contato",
        "form": {
            "heading": "Ou envie os detalhes do projeto",
            "lede": "Informe o objetivo do projeto e o público a que ele se destina.",
            "name": "Nome",
            "email": "E-mail",
            "phone": "WhatsApp (opcional)",
            "type": "Tipo de projeto",
            "type_placeholder": "Selecione…",
            "types": ["Landing page", "Site institucional", "Identidade visual", "Motion e 3D", "Outro"],
            "message": "Sobre o projeto",
            "message_placeholder": "Objetivo, público e prazo desejado.",
            "consent_before": "Concordo com o tratamento dos meus dados para receber retorno sobre este projeto, conforme a ",
            "consent_link": "Política de Privacidade",
            "consent_after": ".",
            "submit": "ENVIAR MENSAGEM",
            "sending": "ENVIANDO…",
            "required": "Preencha este campo.",
            "invalid_email": "Informe um e-mail válido.",
            "consent_required": "Marque a caixa de consentimento para continuar.",
            "success_title": "Mensagem enviada.",
            "success_text": "Obrigado pelo contato. Responderei com os próximos passos do projeto.",
            "error": "Não foi possível enviar a mensagem agora. Tente novamente ou utilize um dos canais abaixo.",
            "not_configured": "O formulário ainda não está conectado a um destino. [PREENCHER: endpoint do formulário]",
            "honeypot": "Não preencha este campo",
        },
    },
    "footer": {"where": "ERICK SOUZA · SÃO PAULO, SP, BRASIL", "privacy": "PRIVACIDADE", "jobs": "VAGAS: LINKEDIN", "year": "© 2026"},
    "case": {
        "title": "DMR Info, TI corporativa e segurança cibernética | Erick Souza",
        "description": "Nova presença digital para uma empresa de tecnologia e segurança eletrônica de São Paulo, entregue em 4 dias.",
        "label": "PROJETO 01 / DMR INFO",
        "h1": "DMR Info",
        "summary": "Nova presença digital para uma empresa de tecnologia e segurança eletrônica de São Paulo, entregue em 4 dias.",
        "meta": [
            ("SEGMENTO", "TI corporativa e segurança cibernética"),
            ("ENTREGA", "4 dias, em agosto de 2026, com fluxo assistido por IA"),
            ("SERVIÇOS", "Identidade visual, UX e UI, motion e desenvolvimento com SEO"),
            ("NO AR", "www.dmrinfo.com.br"),
        ],
        "shot_desktop_alt": "Página inicial do site da DMR Info no desktop",
        "shot_mobile_alt": "Página inicial do site da DMR Info no celular",
        "challenge_label": "DESAFIO",
        "challenge_title": "Visibilidade online.",
        "challenge": "A DMR precisava de visibilidade online e de maior reconhecimento de marca no ambiente digital.",
        "did_label": "ESCOPO",
        "did_title": "Do conceito à publicação.",
        "did": [
            "Identidade visual e posicionamento de marca",
            "UX e UI",
            "Motion",
            "Desenvolvimento do site com SEO e chamadas para ação pensadas para gerar contato",
        ],
        "decisions_label": "DECISÕES",
        "decisions_title": "Decisões de projeto.",
        "decisions": "A identidade visual, o posicionamento da marca e a posição e o texto dos CTAs.",
        "metrics_label": "MEDIÇÕES",
        "metrics_title": "Desempenho técnico.",
        "metrics": [
            ("SEO", "100", "Lighthouse mobile"),
            ("ACESSIBILIDADE", "98", "Lighthouse mobile"),
            ("BOAS PRÁTICAS", "96", "Lighthouse mobile"),
            ("LCP", "1,33 s", "Maior elemento visível"),
            ("CLS", "0,00", "Deslocamento de layout"),
        ],
        "business": ("RESULTADO COMERCIAL", "[PREENCHER]", "Leads, contatos ou vendas, quando a DMR compartilhar números"),
        "metrics_note": "Medido em laboratório, com Lighthouse mobile e trace de performance, em 2026-09-20. Não são dados de usuários reais.",
        "visit": "VER SITE NO AR →",
        "cta_title": "Precisa de um projeto semelhante?",
        "cta_button": "AGENDAR CONVERSA",
        "back": "← VOLTAR AOS PROJETOS",
    },
    "privacy": {
        "title": "Política de privacidade | Erick Souza",
        "description": "Como este site trata dados pessoais.",
        "label": "PRIVACIDADE",
        "h1": "Política de privacidade",
        "intro": "Esta página descreve como este site trata dados pessoais. [PREENCHER: texto revisado por profissional jurídico antes de publicar.]",
        "sections": [
            ("Quais dados são coletados", "[PREENCHER: por exemplo, nome e e-mail enviados por formulário ou agendamento, e dados de navegação, se houver analytics.]"),
            ("Para que são usados", "[PREENCHER: finalidade de cada dado.]"),
            ("Cookies e analytics", "[PREENCHER: ferramenta escolhida e base legal.]"),
            ("Seus direitos (LGPD)", "[PREENCHER: direitos do titular e canal para exercê-los.]"),
            ("Contato do responsável", "Erick Souza · São Paulo, SP, Brasil · [PREENCHER: e-mail]"),
        ],
    },
    "notfound": {
        "title": "404 | Erick Souza",
        "description": "Página não encontrada.",
        "label": "ERRO 404",
        "h1": "Página não encontrada.",
        "text": "O endereço não existe ou foi movido. Volte ao início para continuar navegando.",
        "button": "VOLTAR AO INÍCIO",
    },
}

EN = {
    "code": "en",
    "html_lang": "en",
    "title": "Erick Souza | High-Converting Landing Pages & Web Design",
    "description": "Designer with 20+ years of experience. Landing pages and corporate websites that integrate brand identity, UX, motion and code. Serving clients in Brazil and abroad.",
    "skip": "Skip to content",
    "brand": "ERICK SOUZA",
    "studio": ("UI/UX", "MOTION · BRANDING · WEB"),
    "cta_head": "BOOK A CALL",
    "lang_group_label": "Language",
    "nav_label": "Main navigation",
    "nav": [("projetos", "Projects"), ("servicos", "Services"), ("processo", "Process"), ("sobre", "About"), ("contato", "Contact")],
    "meter": "PROGRESS",
    "loader": {"status": "LOADING"},
    "hero": {
        "label": "01 / ERICK SOUZA",
        "lines": ["Landing pages", "built to convert", "visitors into"],
        "last_lead": "",
        "fault": "clients.",
        "aria": "Landing pages built to convert visitors into clients.",
        "sub": "I'm Erick Souza, a designer with over 20 years of experience. I combine brand identity, UX, motion and code in pages with a clear objective and a focus on the visitor's action.",
        "cta1": "BOOK A CALL",
        "cta2": "SEE MY WORK",
        "readouts": ["SÃO PAULO / BRAZIL", "INTERNATIONAL CLIENTS", "IDENTITY · UX · MOTION · CODE"],
        "call_off": "SCROLL TO CONTINUE",
        "call_on": "SCROLL TO CONTINUE",
    },
    "projects": {
        "label": "02 / PROJECTS",
        "aside": "7 PROJECT TYPES / EXAMPLES COMING SOON",
        "heading": "Project types",
        "conceptual": "EXAMPLES COMING SOON",
        "cards": [
            {"no": "TYPE 01 / INSTITUTIONAL WEBSITES", "name": ["Institutional", "Websites"], "desc": "Full digital presence: company, services and contact, built to earn trust.", "real": False},
            {"no": "TYPE 02 / LANDING PAGE", "name": ["Landing", "Page"], "desc": "One page, one goal: turn visitors into leads or customers.", "real": False},
            {"no": "TYPE 03 / SALES PAGE", "name": ["Sales", "Page"], "desc": "Copy and design structured to present the offer and close the sale.", "real": False},
            {"no": "TYPE 04 / LEAD CAPTURE PAGE", "name": ["Lead Capture", "Page"], "desc": "Lean page trading a contact for something of value: ebook, class or consultation.", "real": False},
            {"no": "TYPE 05 / E-COMMERCE", "name": ["E-commerce"], "desc": "Online store with catalog, checkout and a purchase flow built for conversion.", "real": False},
            {"no": "TYPE 06 / BRANDING", "name": ["Branding"], "desc": "Positioning, voice and a visual system kept consistent across every touchpoint with the brand.", "real": False},
            {"no": "TYPE 07 / VISUAL IDENTITY", "name": ["Visual", "Identity"], "desc": "Logo and graphic elements that give the brand its own identity.", "real": False},
        ],
        "img_alt": "Home page of the DMR Info website, designed by Erick Souza",
        "placeholder": "[FILL IN: example]",
        "banner_label": "Visit the site of DMR Info (opens in a new tab)",
        "banner_cap": "VISIT THE SITE ↗",
    },
    "services": {
        "label": "03 / SERVICES",
        "title": ["From landing pages", "to e-commerce,", "piece by piece."],
        "items": [
            ("01 / BRANDING", "Branding", "Positioning, voice and a brand system that hold every piece of communication together."),
            ("02 / IDENTITY", "Visual identity", "A logo and visual system that support the website and everything that comes after it."),
            ("03 / PRESENCE", "Corporate websites", "The digital presence that introduces the company, what it does and why it deserves trust. Fast, clear and optimized for search engines."),
            ("04 / CONVERSION", "Landing page", "One page, one goal. Structure, copy, design and code built to lead the visitor to a single action."),
            ("05 / SALES", "Sales page", "Copy and design structured to present the offer and close the sale."),
            ("06 / CAPTURE", "Lead capture page", "Lean page trading a contact for something of value: ebook, class or consultation."),
            ("07 / STORE", "E-commerce", "Online store with catalog, checkout and a purchase flow optimized for conversion."),
            ("08 / MOTION", "Motion and 3D", "Animation and 3D elements that give the page rhythm, without compromising performance."),
        ],
    },
    "process": {
        "label": "04 / PROCESS",
        "title": ["From brief", "to launch,", "in one process."],
        "lede": "No step is omitted. Each phase reduces rework in the next.",
        "ai_note": "I use AI as a productivity tool. Strategy and design decisions are mine.",
        "deadline": "TYPICAL LANDING PAGE TIMELINE: [FILL IN]",
        "status_step": "STEP",
        "status_hint": "SCROLL TO ADVANCE",
        "steps": [
            ("Brief", "Review of the business, the audience and what the page needs to achieve."),
            ("Documentation", "Scope, deliverables and expectations recorded in writing."),
            ("Strategy", "Definition of the value proposition, the audience and the main action."),
            ("Wireframe", "Page structure defined before aesthetics."),
            ("Copy", "Writing or revising the text, with a defined role for every block."),
            ("Design", "Identity, typography, color and visual rhythm."),
            ("Prototype", "Review of a clickable prototype before development begins."),
            ("Development", "Clean, fast code structured for SEO."),
            ("Testing", "Speed, accessibility, responsiveness and forms."),
            ("Deploy", "Launch, final verification and handover."),
        ],
    },
    "about": {
        "label": "05 / ABOUT",
        "title": ["20+ years", "of brands.", "Now on the web."],
        "paras": [
            "I have worked in brand design for over 20 years, especially logos. I learned that an effective brand fits inside a simple shape, and that the shape only works when it communicates clearly.",
            "I have also worked in social media, which taught me to design for short attention: every element has to justify its place.",
            "Today I apply that experience to the digital environment. I take on identity, layout, motion and development, with a single point of contact from brief to launch.",
            "I bring to digital the same rigor I have always applied to brand work: every project is handled with judgment and delivered with care.",
        ],
        "meta": "SÃO PAULO, SP · 20+ YEARS OF DESIGN · UI/UX · MOTION · BRANDING · WEB",
        "portrait": "[FILL IN: portrait of Erick]",
        "workshop": "[FILL IN: photo of the process or workspace]",
    },
    "tools": {
        "label": "06 / TOOLS",
        "heading": "Tools",
        "quote": "The tools I use across design, motion and development.",
        "groups": [
            ("DESIGN AND MOTION", "Figma, Photoshop, Spline, Premiere, CapCut, Topaz Video"),
            ("DEVELOPMENT", "HTML5, CSS3, Sass, JavaScript, TypeScript, React, PHP, MySQL, GSAP, Anime.js, Barba.js, GitHub"),
            ("AI", "Claude Code, ChatGPT, Kling AI"),
        ],
    },
    "contact": {
        "label": "07 / CONTACT",
        "h2_before": "Shall we discuss the project your ",
        "h2_word": "brand",
        "h2_after": " needs",
        "text": "Describe the project's objective. I'll reply with the next steps.",
        "button": "BOOK A CALL →",
        "channels": [
            ("E-mail", "[FILL IN]"),
            ("WhatsApp", "[FILL IN]"),
            ("Scheduling", "[FILL IN]"),
            ("LinkedIn", "Full-time roles [FILL IN]"),
            ("GitHub", "[FILL IN]"),
            ("Behance", "[FILL IN]"),
            ("Dribbble", "[FILL IN]"),
            ("Instagram", "[FILL IN]"),
        ],
        "channels_label": "Contact channels",
        "form": {
            "heading": "Or send the project details",
            "lede": "State the project's objective and its target audience.",
            "name": "Name",
            "email": "E-mail",
            "phone": "WhatsApp (optional)",
            "type": "Project type",
            "type_placeholder": "Select…",
            "types": ["Landing page", "Corporate website", "Visual identity", "Motion and 3D", "Other"],
            "message": "About the project",
            "message_placeholder": "Objective, audience and desired timeline.",
            "consent_before": "I agree to the processing of my data so I can get a reply about this project, as described in the ",
            "consent_link": "Privacy Policy",
            "consent_after": ".",
            "submit": "SEND MESSAGE",
            "sending": "SENDING…",
            "required": "Please fill in this field.",
            "invalid_email": "Enter a valid e-mail address.",
            "consent_required": "Tick the consent box to continue.",
            "success_title": "Message sent.",
            "success_text": "Thank you for getting in touch. I'll reply with the next steps for your project.",
            "error": "The message could not be sent right now. Please try again or use one of the channels below.",
            "not_configured": "The form is not connected to a destination yet. [FILL IN: form endpoint]",
            "honeypot": "Do not fill in this field",
        },
    },
    "footer": {"where": "ERICK SOUZA · SÃO PAULO, SP, BRAZIL", "privacy": "PRIVACY", "jobs": "JOBS: LINKEDIN", "year": "© 2026"},
    "case": {
        "title": "DMR Info, corporate IT and cybersecurity | Erick Souza",
        "description": "A new digital presence for a São Paulo technology and electronic security company, delivered in 4 days.",
        "label": "PROJECT 01 / DMR INFO",
        "h1": "DMR Info",
        "summary": "A new digital presence for a São Paulo technology and electronic security company, delivered in 4 days.",
        "meta": [
            ("SEGMENT", "Corporate IT and cybersecurity"),
            ("DELIVERY", "4 days, in August 2026, with an AI-assisted workflow"),
            ("SERVICES", "Visual identity, UX and UI, motion and development with SEO"),
            ("LIVE", "www.dmrinfo.com.br"),
        ],
        "shot_desktop_alt": "Home page of the DMR Info website on desktop",
        "shot_mobile_alt": "Home page of the DMR Info website on mobile",
        "challenge_label": "CHALLENGE",
        "challenge_title": "Online visibility.",
        "challenge": "DMR needed online visibility and stronger brand recognition in the digital environment.",
        "did_label": "SCOPE",
        "did_title": "From concept to launch.",
        "did": [
            "Visual identity and brand positioning",
            "UX and UI",
            "Motion",
            "A website built with SEO and calls to action designed to generate contact",
        ],
        "decisions_label": "DECISIONS",
        "decisions_title": "Design decisions.",
        "decisions": "The visual identity, the brand positioning, and the placement and wording of the CTAs.",
        "metrics_label": "MEASUREMENTS",
        "metrics_title": "Technical performance.",
        "metrics": [
            ("SEO", "100", "Lighthouse mobile"),
            ("ACCESSIBILITY", "98", "Lighthouse mobile"),
            ("BEST PRACTICES", "96", "Lighthouse mobile"),
            ("LCP", "1.33 s", "Largest contentful paint"),
            ("CLS", "0.00", "Layout shift"),
        ],
        "business": ("BUSINESS RESULTS", "[FILL IN]", "Leads, inquiries or sales, once DMR shares numbers"),
        "metrics_note": "Measured in lab conditions, with Lighthouse mobile and a performance trace, on 2026-09-20. Not real-user data.",
        "visit": "VISIT THE LIVE SITE →",
        "cta_title": "Need a similar project?",
        "cta_button": "BOOK A CALL",
        "back": "← BACK TO PROJECTS",
    },
    "privacy": {
        "title": "Privacy policy | Erick Souza",
        "description": "How this website handles personal data.",
        "label": "PRIVACY",
        "h1": "Privacy policy",
        "intro": "This page describes how this website handles personal data. [FILL IN: text reviewed by a legal professional before publishing.]",
        "sections": [
            ("What data is collected", "[FILL IN: for example, name and e-mail sent through a form or scheduling tool, and browsing data if analytics is used.]"),
            ("What it is used for", "[FILL IN: purpose of each data point.]"),
            ("Cookies and analytics", "[FILL IN: chosen tool and legal basis.]"),
            ("Your rights (LGPD)", "[FILL IN: data subject rights and how to exercise them.]"),
            ("Controller contact", "Erick Souza · São Paulo, SP, Brazil · [FILL IN: e-mail]"),
        ],
    },
    "notfound": {
        "title": "404 | Erick Souza",
        "description": "Page not found.",
        "label": "ERROR 404",
        "h1": "Page not found.",
        "text": "The address doesn't exist or has moved. Return to the start to keep browsing.",
        "button": "BACK TO START",
    },
}

ES = {
    "code": "es",
    "html_lang": "es",
    "title": "Erick Souza | Landing Pages de Alta Conversión y Diseño Web",
    "description": "Diseñador con más de 20 años de experiencia. Landing pages y sitios corporativos que integran identidad visual, UX, motion y código. Atención a clientes en Brasil y en el exterior.",
    "skip": "Saltar al contenido",
    "brand": "ERICK SOUZA",
    "studio": ("UI/UX", "MOTION · BRANDING · WEB"),
    "cta_head": "AGENDAR LLAMADA",
    "lang_group_label": "Idioma",
    "nav_label": "Navegación principal",
    "nav": [("projetos", "Proyectos"), ("servicos", "Servicios"), ("processo", "Proceso"), ("sobre", "Sobre mí"), ("contato", "Contacto")],
    "meter": "PROGRESO",
    "loader": {"status": "CARGANDO"},
    "hero": {
        "label": "01 / ERICK SOUZA",
        "lines": ["Landing pages", "diseñadas para", "convertir visitas"],
        "last_lead": "en ",
        "fault": "clientes.",
        "aria": "Landing pages diseñadas para convertir visitas en clientes.",
        "sub": "Soy Erick Souza, diseñador desde hace más de 20 años. Integro identidad visual, UX, motion y código en páginas con un objetivo claro y foco en la acción del visitante.",
        "cta1": "AGENDAR UNA LLAMADA",
        "cta2": "VER PROYECTOS",
        "readouts": ["SÃO PAULO / BRASIL", "ATENCIÓN INTERNACIONAL", "IDENTIDAD · UX · MOTION · CÓDIGO"],
        "call_off": "DESLICE PARA CONTINUAR",
        "call_on": "DESLICE PARA CONTINUAR",
    },
    "projects": {
        "label": "02 / PROYECTOS",
        "aside": "7 TIPOS DE PROYECTO / EJEMPLOS PRÓXIMAMENTE",
        "heading": "Tipos de proyecto",
        "conceptual": "EJEMPLOS PRÓXIMAMENTE",
        "cards": [
            {"no": "TIPO 01 / SITIOS INSTITUCIONALES", "name": ["Sitios", "Institucionales"], "desc": "Presencia digital completa: empresa, servicios y contacto, pensada para generar confianza.", "real": False},
            {"no": "TIPO 02 / LANDING PAGE", "name": ["Landing", "Page"], "desc": "Una página, un objetivo: convertir visitas en leads o clientes.", "real": False},
            {"no": "TIPO 03 / PÁGINA DE VENTAS", "name": ["Página de", "Ventas"], "desc": "Copy y diseño estructurados para presentar la oferta y cerrar la venta.", "real": False},
            {"no": "TIPO 04 / PÁGINA DE CAPTURA", "name": ["Página de", "Captura"], "desc": "Página ligera que intercambia un contacto por algo de valor: ebook, clase o consultoría.", "real": False},
            {"no": "TIPO 05 / E-COMMERCE", "name": ["E-commerce"], "desc": "Tienda virtual con catálogo, checkout y experiencia de compra optimizada para conversión.", "real": False},
            {"no": "TIPO 06 / BRANDING", "name": ["Branding"], "desc": "Posicionamiento, tono de voz y sistema visual coherentes en cada punto de contacto con la marca.", "real": False},
            {"no": "TIPO 07 / IDENTIDAD VISUAL", "name": ["Identidad", "Visual"], "desc": "Logotipo y elementos gráficos que dan identidad propia a la marca.", "real": False},
        ],
        "img_alt": "Página de inicio del sitio de DMR Info, diseñada por Erick Souza",
        "placeholder": "[COMPLETAR: ejemplo]",
        "banner_label": "Visitar el sitio de DMR Info (se abre en una pestaña nueva)",
        "banner_cap": "VISITAR EL SITIO ↗",
    },
    "services": {
        "label": "03 / SERVICIOS",
        "title": ["De landing pages", "a e-commerce,", "pieza por pieza."],
        "items": [
            ("01 / BRANDING", "Branding", "Posicionamiento, tono de voz y sistema de marca que sostienen toda la comunicación."),
            ("02 / IDENTIDAD", "Identidad visual", "Un logotipo y un sistema visual que sostienen el sitio y todo lo que viene después."),
            ("03 / PRESENCIA", "Sitios corporativos", "La presencia digital que presenta a la empresa, lo que hace y por qué merece confianza. Rápida, clara y optimizada para los buscadores."),
            ("04 / CONVERSIÓN", "Landing page", "Una página, un objetivo. Estructura, texto, diseño y código pensados para llevar al visitante a una única acción."),
            ("05 / VENTAS", "Página de ventas", "Copy y diseño estructurados para presentar la oferta y cerrar la venta."),
            ("06 / CAPTURA", "Página de captura", "Página ligera que intercambia un contacto por algo de valor: ebook, clase o consultoría."),
            ("07 / TIENDA", "E-commerce", "Tienda virtual con catálogo, checkout y experiencia de compra optimizada para conversión."),
            ("08 / MOVIMIENTO", "Motion y 3D", "Animación y elementos 3D que dan ritmo a la página, sin comprometer el rendimiento."),
        ],
    },
    "process": {
        "label": "04 / PROCESO",
        "title": ["Del briefing", "a la publicación,", "en un solo proceso."],
        "lede": "No se omite ningún paso. Cada fase reduce el retrabajo de la siguiente.",
        "ai_note": "Utilizo la IA como herramienta de productividad. Las decisiones de estrategia y de diseño son mías.",
        "deadline": "PLAZO TÍPICO DE UNA LANDING PAGE: [COMPLETAR]",
        "status_step": "PASO",
        "status_hint": "DESLIZA PARA AVANZAR",
        "steps": [
            ("Briefing", "Levantamiento del negocio, del público y de lo que la página necesita lograr."),
            ("Documentación", "Alcance, entregables y expectativas registrados por escrito."),
            ("Estrategia", "Definición de la propuesta de valor, del público y de la acción principal."),
            ("Wireframe", "Estructura de la página definida antes de la estética."),
            ("Copy", "Redacción o revisión de los textos, con una función definida para cada bloque."),
            ("Diseño", "Identidad, tipografía, color y ritmo visual."),
            ("Prototipado", "Validación de un prototipo navegable antes de iniciar el desarrollo."),
            ("Desarrollo", "Código limpio, rápido y estructurado para SEO."),
            ("Pruebas", "Velocidad, accesibilidad, adaptación a pantallas y formularios."),
            ("Despliegue", "Publicación, verificación final y entrega."),
        ],
    },
    "about": {
        "label": "05 / SOBRE MÍ",
        "title": ["20+ años", "de marcas.", "Ahora en la web."],
        "paras": [
            "Trabajo desde hace más de 20 años en diseño de marcas, especialmente logotipos. Aprendí que una marca eficaz cabe en una forma simple, y que esa forma solo funciona cuando comunica con claridad.",
            "También trabajé en redes sociales, lo que me enseñó a diseñar para una atención breve: cada elemento debe justificar su lugar.",
            "Hoy aplico esa experiencia al entorno digital. Me encargo de la identidad, el layout, el motion y el desarrollo, con un único punto de contacto desde el briefing hasta la publicación.",
            "Llevo a lo digital el mismo rigor que siempre apliqué al trabajo con marcas: cada proyecto se conduce con criterio y se entrega con cuidado.",
        ],
        "meta": "SÃO PAULO, SP · 20+ AÑOS DE DISEÑO · UI/UX · MOTION · BRANDING · WEB",
        "portrait": "[COMPLETAR: retrato de Erick]",
        "workshop": "[COMPLETAR: foto del proceso o del espacio de trabajo]",
    },
    "tools": {
        "label": "06 / HERRAMIENTAS",
        "heading": "Herramientas",
        "quote": "Las herramientas que utilizo en diseño, motion y desarrollo.",
        "groups": [
            ("DISEÑO Y MOTION", "Figma, Photoshop, Spline, Premiere, CapCut, Topaz Video"),
            ("DESARROLLO", "HTML5, CSS3, Sass, JavaScript, TypeScript, React, PHP, MySQL, GSAP, Anime.js, Barba.js, GitHub"),
            ("IA", "Claude Code, ChatGPT, Kling AI"),
        ],
    },
    "contact": {
        "label": "07 / CONTACTO",
        "h2_before": "¿Hablamos sobre el proyecto de su ",
        "h2_word": "marca",
        "h2_after": "",
        "text": "Describa el objetivo del proyecto. Responderé con los próximos pasos.",
        "button": "AGENDAR UNA LLAMADA →",
        "channels": [
            ("E-mail", "[COMPLETAR]"),
            ("WhatsApp", "[COMPLETAR]"),
            ("Agenda", "[COMPLETAR]"),
            ("LinkedIn", "Empleos [COMPLETAR]"),
            ("GitHub", "[COMPLETAR]"),
            ("Behance", "[COMPLETAR]"),
            ("Dribbble", "[COMPLETAR]"),
            ("Instagram", "[COMPLETAR]"),
        ],
        "channels_label": "Canales de contacto",
        "form": {
            "heading": "O envíe los detalles del proyecto",
            "lede": "Indique el objetivo del proyecto y el público al que se dirige.",
            "name": "Nombre",
            "email": "E-mail",
            "phone": "WhatsApp (opcional)",
            "type": "Tipo de proyecto",
            "type_placeholder": "Seleccione…",
            "types": ["Landing page", "Sitio corporativo", "Identidad visual", "Motion y 3D", "Otro"],
            "message": "Sobre el proyecto",
            "message_placeholder": "Objetivo, público y plazo deseado.",
            "consent_before": "Acepto el tratamiento de mis datos para recibir respuesta sobre este proyecto, según la ",
            "consent_link": "Política de privacidad",
            "consent_after": ".",
            "submit": "ENVIAR MENSAJE",
            "sending": "ENVIANDO…",
            "required": "Complete este campo.",
            "invalid_email": "Ingrese un e-mail válido.",
            "consent_required": "Marque la casilla de consentimiento para continuar.",
            "success_title": "Mensaje enviado.",
            "success_text": "Gracias por su contacto. Responderé con los próximos pasos de su proyecto.",
            "error": "No fue posible enviar el mensaje ahora. Inténtelo de nuevo o utilice uno de los canales de abajo.",
            "not_configured": "El formulario aún no está conectado a un destino. [COMPLETAR: endpoint del formulario]",
            "honeypot": "No completes este campo",
        },
    },
    "footer": {"where": "ERICK SOUZA · SÃO PAULO, SP, BRASIL", "privacy": "PRIVACIDAD", "jobs": "EMPLEOS: LINKEDIN", "year": "© 2026"},
    "case": {
        "title": "DMR Info, TI corporativa y ciberseguridad | Erick Souza",
        "description": "Una nueva presencia digital para una empresa de tecnología y seguridad electrónica de São Paulo, entregada en 4 días.",
        "label": "PROYECTO 01 / DMR INFO",
        "h1": "DMR Info",
        "summary": "Una nueva presencia digital para una empresa de tecnología y seguridad electrónica de São Paulo, entregada en 4 días.",
        "meta": [
            ("SEGMENTO", "TI corporativa y ciberseguridad"),
            ("ENTREGA", "4 días, en agosto de 2026, con flujo asistido por IA"),
            ("SERVICIOS", "Identidad visual, UX y UI, motion y desarrollo con SEO"),
            ("EN VIVO", "www.dmrinfo.com.br"),
        ],
        "shot_desktop_alt": "Página de inicio del sitio de DMR Info en escritorio",
        "shot_mobile_alt": "Página de inicio del sitio de DMR Info en el celular",
        "challenge_label": "DESAFÍO",
        "challenge_title": "Visibilidad en línea.",
        "challenge": "DMR necesitaba visibilidad en línea y mayor reconocimiento de marca en el entorno digital.",
        "did_label": "ALCANCE",
        "did_title": "Del concepto a la publicación.",
        "did": [
            "Identidad visual y posicionamiento de marca",
            "UX y UI",
            "Motion",
            "Desarrollo del sitio con SEO y llamadas a la acción pensadas para generar contacto",
        ],
        "decisions_label": "DECISIONES",
        "decisions_title": "Decisiones de proyecto.",
        "decisions": "La identidad visual, el posicionamiento de la marca y la posición y el texto de los CTA.",
        "metrics_label": "MEDICIONES",
        "metrics_title": "Rendimiento técnico.",
        "metrics": [
            ("SEO", "100", "Lighthouse mobile"),
            ("ACCESIBILIDAD", "98", "Lighthouse mobile"),
            ("BUENAS PRÁCTICAS", "96", "Lighthouse mobile"),
            ("LCP", "1,33 s", "Elemento visible más grande"),
            ("CLS", "0,00", "Desplazamiento de diseño"),
        ],
        "business": ("RESULTADO COMERCIAL", "[COMPLETAR]", "Leads, contactos o ventas, cuando DMR comparta números"),
        "metrics_note": "Medido en laboratorio, con Lighthouse mobile y un trace de rendimiento, el 2026-09-20. No son datos de usuarios reales.",
        "visit": "VER EL SITIO EN VIVO →",
        "cta_title": "¿Necesita un proyecto similar?",
        "cta_button": "AGENDAR UNA LLAMADA",
        "back": "← VOLVER A PROYECTOS",
    },
    "privacy": {
        "title": "Política de privacidad | Erick Souza",
        "description": "Cómo este sitio trata los datos personales.",
        "label": "PRIVACIDAD",
        "h1": "Política de privacidad",
        "intro": "Esta página describe cómo este sitio trata los datos personales. [COMPLETAR: texto revisado por un profesional jurídico antes de publicar.]",
        "sections": [
            ("Qué datos se recopilan", "[COMPLETAR: por ejemplo, nombre y correo enviados por formulario o agenda, y datos de navegación si hay analítica.]"),
            ("Para qué se usan", "[COMPLETAR: finalidad de cada dato.]"),
            ("Cookies y analítica", "[COMPLETAR: herramienta elegida y base legal.]"),
            ("Tus derechos (LGPD)", "[COMPLETAR: derechos del titular y cómo ejercerlos.]"),
            ("Contacto del responsable", "Erick Souza · São Paulo, SP, Brasil · [COMPLETAR: e-mail]"),
        ],
    },
    "notfound": {
        "title": "404 | Erick Souza",
        "description": "Página no encontrada.",
        "label": "ERROR 404",
        "h1": "Página no encontrada.",
        "text": "La dirección no existe o se movió. Vuelva al inicio para seguir navegando.",
        "button": "VOLVER AL INICIO",
    },
}

LANGS = {"pt": PT, "en": EN, "es": ES}
